In [3]:
using Plots
using LinearAlgebra
using Statistics

In [1]:
t = collect(1:8)

8-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8

In [8]:
t2 = reshape(t, 2, 2, 2)
T = []

for i in 1:2
    for j in 1:2
        for k in 1:2 
            println(t2[i, j, k])
        end
    end
end

1
5
3
7
2
6
4
8


In [70]:
A = Array{Int}(undef, 10)

A[1:2:end] = [1,1,1,1,1]
A[2:2:end] = [2,2,2,2,2]
A

10-element Vector{Int64}:
 1
 2
 1
 2
 1
 2
 1
 2
 1
 2

In [71]:
E = zeros(3, 3)

for i in 1:3
    E[i,i] = 1.0
end
E

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [72]:
A = [4 8 12; 16 20 24; 28 32 36]
B = [2 2 2; 4 4 4; 8 8 8]

A ./ B

3×3 Matrix{Float64}:
 2.0  4.0  6.0
 4.0  5.0  6.0
 3.5  4.0  4.5

In [73]:
matrix = [
    1 2 3;
    4 5 6;
    7 8 9
]

matrix1 = matrix[1:1, :]
matrix3 = matrix[3:3, :]
matrix[1:1, :] = matrix3
matrix[3:3, :] = matrix1
matrix

3×3 Matrix{Int64}:
 7  8  9
 4  5  6
 1  2  3

In [74]:
matrix = [
    3 6 9;
    12 15 18;
    21 24 27
]

matrix_ = reshape(matrix, 9)

9-element Vector{Int64}:
  3
 12
 21
  6
 15
 24
  9
 18
 27